[package]
name = "lcf-explorer"
version = "0.2.0"
edition = "2024"
publish = false

[dependencies]
eframe = "0.32.0"
egui = "0.32.0"
egui_ltreeview = "0.5.3"
encoding_rs = "0.8.35"
lcf = "0.6.0"
rfd = "0.15.4"
